### ISSUE TITLE
Проблема буферизации вывода при обновлении страницы.

### ISSUE THREAD

**Issue by samheap** [JoCat/IcePlayer#1]
Спасибо за вашу работу.
Установил ваш плеер на сайт https://www.mixto.ru/radio/ .
Заметил неприятный момент связанный с буферизацией. Если при воспроизведении потока обновить страницу (F5), то нарушается нормальное звучание, а куски потока перемешиваются. Получается "не айс"! :)
Наверное это вызвано оставшимися в буфере данными?
При нажатии на PLAY, СТОП, ПАУЗУ вы не очищаете буфер?
Что можете посоветовать для решения проблемы?
Спасибо.

**Comment by JoCat** [comment]
Насколько я знаю такое проявляется только в браузере Firefox, не разбирался в чем причина из-за того что скриптом в принципе никто давно не пользовался, возможно какие-то проблемы с кэшем.

Там по сути всё построено на апи тега audio только со стороны js, и работать должен точно так же. Посмотрю на днях в чём причина такого поведения.

**Comment by JoCat** [comment]
Ну да, кривая работа кэширования в Firefox
Это так и не пофиксили, а уже 6 лет прошло))

https://stackoverflow.com/questions/28245407/audio-and-mozilla-firefox-cache-issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1129121

В общем пришлось костыльнуть)
