### ISSUE TITLE
Несколько плееров на одной странице. Как?

### ISSUE THREAD

**Issue by samheap** [JoCat/IcePlayer#2]
Вы рассматривали вариант установки нескольких плееров на одной странице? 
Если да, то как?
Спасибо.

**Comment by JoCat** [comment]
Можно реализовать путём инициализации нескольких копий плееров, единственное это по сути будут отдельные плеера и не получится сделать например общую паузу при запуске другого плеера, хотяяя...
В любом случае для этого нужно немного поправить код, чем я займусь в ближайшее время

**Comment by JoCat** [comment]
Фичу добавлю в релиз, но ты в принципе можешь взять скрипт из [dev](https://github.com/JoCat/IcePlayer/tree/dev) ветки.
В папке demo лежит пример использования.
